### ISSUE TITLE
Improve Search

### ISSUE THREAD

**Issue by Marvellanius** [ilestis/miscellany#11]
# Story
As a user, I want the search to be better.

# Work
1. Adapt the search to also cover entity description and history
2. On the sidebar search box, have a type-ahead (like relations), where clicking on one element goes directly to that element. Otherwise it does the standard search.
3. Adapt the search result page to be more useful if possible?

# Tests
* Searching also looks in description and history
* Sidebar type ahead allows going directly to a desired entity
* Sidebar type ahead works on mobile

**Comment by ilestis** [comment]
Type-ahead kills performances, but searching in several fields has been added. Performance aren't great (like %% on lots of text fields), so the future might be elasticsearch.
