### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by ilestis** [ilestis/miscellany#115]
# Story
As a user, I want the UI to be better.

# Work
* Permissions panel into ajax/modal
* Character and locations: Quests?
* Character: Re-do interface
* Split "generic" and "entity specific" visual information.

**Comment by pspeter3** [comment]
Is there a way that I can help with this?

**Comment by ilestis** [comment]
I have several ideas for this but it's all very unspecific.

Firstly, small improvements to the UI are always nice. I tried doing some changes in a separate branch a month of so ago but wasn't too happy with the changes.

Ultimately I would love to hire a professional designer and UX person to design the UI, and rebuild the whole frontend with tailwind.css and vue.js instead of the current bootstrap3 and jQuery, but it's not a priority at all.

Back on the ticket itself, feel free to submit mock ups or ideas for improvement. The "menu" on each entity view on mobile for example could be switched to a grid instead of a list to gain some space.

**Comment by pspeter3** [comment]
I would be happy to help with the tailwind migration. How does Vue work with the server rendered UI? Or it is using the API?

**Comment by ilestis** [comment]
Reworking the UI with tailwind/vue would wait until I have the funds to hire a professional designer to redesign the app. The idea with vuejs would be to offload html rendering from the server to the frontend, and use the apis instead of the app's controllers.

**Comment by pspeter3** [comment]
Is it possible to fully replicate the UI with the API or is there private functionality?

**Comment by ilestis** [comment]
I guestimate the APIs to only expose 60% of the features of the app currently (for example managing a campaign, campaign roles & members, or entity permissions isn't possible through the API).
