### ISSUE TITLE
Dropdown: Auto load 10 recent entries

### ISSUE THREAD

**Issue by Marvellanius** [ilestis/miscellany#13]
# Story
As a user, when creating or editing an entity that has foreign values (character's location or family), I want the dropdown to be pre-populated with the 10 last options I selected.

# Work
This ticket can be split in two parts: Front-end and Back-end.

1. Adapt the dropdowns (select2) to pre-load some data before hand
2. Make the pre-loaded data recent values for those fields.

# Test
* When creating a character, the family and location dropdown is pre-loaded (I don't have to type in anything) with the 10 previously used values. Clicking on one of the values set the select field.
* Works on mobile
* Same thing works on Location's parent location field.

**Comment by ilestis** [comment]
Ready for prod. No longer has a minimum length and will thus auto-load from the server the last 10 when clicking. Only drawback is that is constantly loads when clicking on the form, which shouldn't impact many users. Maybe increase the `quietMillis` for searching.
