### ISSUE TITLE
Custom calendar system per campaign

### ISSUE THREAD

**Issue by Marvellanius** [ilestis/miscellany#14]
# Story
As a user, I want to be able to create a custom calendar for my campaign. This should be similar to https://donjon.bin.sh/fantasy/calendar/

# Work
1. Create a proposal on how the calendar system should work, what it should track
2. Implement the proposal into the code

# Tests
* A user can create a calendar based of the proposal for his campaign
* A viewer of a campaign can see the calendar
* The calendar can be changed and re-generated

**Comment by ilestis** [comment]
Inspiration:
* https://onitools.moe/reki/
* https://donjon.bin.sh/fantasy/calendar/
* WorldAnvil has one

Comment from ArcOnyx
```First the stuff from Reki I liked (this is most things from Reki):
- Suffixes for eras (e.g. AD, BC)
- Months per year
- Days per week
- Number of moons (ok, not that important)
- Month names and lengths
- Names for the days of the week
- Lunar cycle
- Leap days
- Input summer solstice and derive similar dates from that.
- Current campaign date - I sort of like it, but if I want to play sessions at different points in time this would just get muddled. I guess it just needs to be easy to change in either direction.
Other Random Stuff
- The whole round/minutes/hour thing Reki has seems unnecessary to me for a calendar.
- Being able to give years names would be cool (for instance 5 AD might be the Year of the Flippant Flying Fish)
- The ability to have days that aren't part of months would be interesting (e.g. 19th June, 20th June, Midwinter, 21st June, 22nd June). Not that important to have though.
- Seasons! Start and end seems like the most reliable way to do it. Reki seems to work by setting the summer solstice and calculating it from that, which is an issue if you have five seasons.
- Another insignificant but cool option: Being able to 'reset' the at the start of every month, rather than continuing. You'd go back to the beginning of the week rather than continuing on like in the Gregorian calendar.
- Events (like holidays or the apocalypse). We should be able to set these as single days or a group of days (for five day festivals and the like). The ability to get something up to repeat (e.g. annually) would be rather handy too. For some reason Reki only seems to let you add events relative to the current date (e.g. in 5 days). This is weird and annoying. The ability to just choose a date is much better.
- I do like a traditional month view (what donjon terms a 'block' layout). Can't find one in Reki, which annoys me. Being able to click on events in this view to go to the event would be great.
- The ability to have the date in an event entity link to something like the calendar for that month would be nice.
- Timelines are awesome.
- The ability to see everything associated with a date (events, journals, etc) would be useful. Maybe the date link from a couple of points above could go here.
- Some calendars use leap months. I don't see myself needing it, but someone might.(edited)
```

Comment from whitecodexes:
```Also when you do get into the timeline / calendar features, I think guy it was cool how WorldAnvil had an option to build a custom calendar, then assign it to be used for this timeline/campaign. After that on the timeline, you could use @“#” (without the parentheses) and input the number of the month and it would automatically set the name of the month based on what number you had that month set as.```

**Comment by ilestis** [comment]
sirkerry - Today at 00:32
@Ilestis as long as it supports calendars like the one from Traveller's Third Imperium setting style I'm good with pretty much any calendar implementation: http://wiki.travellerrpg.com/Imperial_Calendar
Imperial Calendar

ArcOnyx - Today at 02:37
That brings up another point - the ability to have multiple calendars per setting would be great. Maybe have a default or primary calendar for links, like from the date in the event entity.
(I've basically been mentioning everything I can think of, regardless of how essential it is.)

whitecodexes - Today at 02:45
I definitely second holidays and events, timelines, and year names. 

If you do decide to add timelines, maybe have them available as categorized events?
I don’t know. I feel like I’m just shouting out a lot of things and it feels bossy.

ArcOnyx - Today at 02:49
Heh, I know the feeling.
With the timelines, what exactly do you mean?
I sort of understand it, but my brain is tired.
Is it populating a timeline from events in a certain category?
Something else?

whitecodexes - Today at 03:10
Ah.  Basically I meant when we create items on the timeline, give them event types.
Kind of like this?

**Comment by ilestis** [comment]
Required feature: Negative leap days!
