### ISSUE TITLE
Media manager: quick interface to see all your uploaded files

### ISSUE THREAD

**Issue by Marvellanius** [ilestis/miscellany#15]
# Story
As a user, I want an interface to quickly see all the images that I have uploaded.

# Work
* Dependency issue #3 
* Create an interface for the user to see his uploaded images. Or use an existing package.

# Tests
* I can see my images
* Works on mobile

**Comment by ilestis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Media Manager](https://trello.com/c/oxidqyeV/18-media-manager)
