### ISSUE TITLE
Notification system: be alerted when someone joins your campaign (and more...)

### ISSUE THREAD

**Issue by Marvellanius** [ilestis/miscellany#16]
# Story
As a user, I want to be notified in the app when some things happen.

# Work
* Build a notification model (probably already exists thousands of them, use plugins if possible?)
* Adapt the frontend to show alerts in the header (using the AdminLTE bootstrap template)
* Send notifications to a campaign owner when someone joins or leaves their campaign.
* Create a cron to delete read notifications after 30 days (part of the plugin?)

# Tests
* Joining a campaign sends a notification to the campaign owner.
* Leaving a campaign sends a notification to the campaign owner.
* Notifications are deleted after 30 days
* Deleting my user deletes my notifications
* Notifications work on mobile

**Comment by ilestis** [comment]
Wrote a notification system based on laravel's Notifications for the new permission system.

**Comment by ilestis** [comment]
Ready for prod.

Examples in the `App\Services\CampaignService` and `App\Services\InviteService` classes.
