### ISSUE TITLE
Linking: instead of the "{entity: name}" syntax, allow "@" à la twitter with live dropdown options

### ISSUE THREAD

**Issue by Marvellanius** [ilestis/miscellany#18]
# Story
As a user, when writing in a rich text box (usually History or Description) of an entity, I want to be able to use the "@entity name" that will create a dropdown for me to select an entity from. Clicking on an entity in the dropdown should create the link directly to that entity.

# Work
1. Create a hook (or use a plugin) for tinymce to fire when "@" is pressed followed by a few characters to suggest a list of entities based on the name. Carefully, several entities can have the same name!

# Test
* Create both a note and a character with the name "George".
* Writting "@Georg" in the rich text area will suggest both elements in the dropdown. Pressing enter selects the first one.
* Selecting an option creates the link directly to that entity (/lang/entityType/id).
* This should work on mobile and tablet

**Comment by ilestis** [comment]
Might have to switch to tinymce and https://github.com/StevenDevooght/tinyMCE-mention

**Comment by Marvellanius** [comment]
tinyMCE does look good, will look into it
