### ISSUE TITLE
Duplicate Campaign option

### ISSUE THREAD

**Issue by Marvellanius** [ilestis/miscellany#19]
# Story
As a user, I want to be able to duplicate a campaign.

# Work
1. Add a "duplicate campaign" button in the campaign view for owners.

# Tests
* Duplicating a campaign edits the name in a way that is easy to distinguish
* Duplicating a campaign duplicates all elements of the databases
* Duplicating a campaign switches the current session campaignId to the new one
* Duplicating a campaign duplicated the settings and members of a campaign
* Duplicating a campaign duplicates the images
* Removing the image of an entity of the duplicated campaign doesn't remove the file of the original (since it should have a new name)
* Duplicating a campaign ad infinitum should not kill the server (no more space)

**Comment by ilestis** [comment]
This could actually be quite an extensive task, so it might be best to have it deferred to a queue system. That way the user eventually gets his duplicate (entities, permissions, etc). That way we can also maybe copy the images, since the script isn't limited by having to reply in a few seconds.

**Comment by ilestis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Campaign: Duplicate](https://trello.com/c/uHlwlLw9/17-campaign-duplicate)
