### ISSUE TITLE
Attributes on each entity

### ISSUE THREAD

**Issue by Marvellanius** [ilestis/miscellany#2]
# Story
As a user, I want to be able to set attributes on other entities, the same way attributes work on *Characters*.

# Work
1. Move the current Attributes code from the Character entity to a generic Crud (very similar to *relations*). This will require a new model using the *entities* table.
2. Create a migration that moves the character attributes to the new attributes table
3. Add the Attributes tab and code to the following entities: Locations, Families, Events and Organisations. 
4. Remove the attributes code specifically targeted to Characters, using the new generic code instead.
5. Moving entities should keep all the attributes

# Tests
* I can create, update and delete cruds on Characters, Locations, Families, Events and Organisations
* Attributes created on characters before the change are still viewable, editable and deletable.
* The character_attribute table no longer exists
* Moving an entity with attributes to another keeps the attributes.
* Moving an entity with attributes to another without attributes keeps the attributes none the less.

**Comment by ilestis** [comment]
Ready for prod. Backup db before (since it deletes the old attributes from characters and locations)
