### ISSUE TITLE
Map: Being able to upload a map of your campaign, and create links on it to various entities

### ISSUE THREAD

**Issue by Marvellanius** [ilestis/miscellany#20]
# Story
As a user, I want to be able to upload a high resolution maps of my campaign, and be able to add links on it to locations.

# Work
1. As a new "Maps" entry in the sidebar, with a new crud for the Maps of a campaign. Create a new model and db.
2. Allow the admin and member of a campaign to upload images of the campaign to the server. 
3. Once the image is uploaded, allow admins and members to zoom in and out of the map
4. Allow admins and members to add/edit/delete links to locations by clicking on the map
5. Allow viewers to see the map
6. The Map feature of a campaign can be disabled in the campaign settings.

# Tests
* Maps of a campaign can be uploaded to the server
* Locations can be added to maps
* Viewers can see maps, zoom in and out, but can't add or alter maps
* Maps work on mobile
* An admin can disable maps from the campaign, hiding them from the interface completely.

**Comment by ilestis** [comment]
Overflow problems on big maps
Create a new location in the modal
Control the size of the point
Mobile rendering?
