### ISSUE TITLE
Elements: Ability to attach several files to an entity (several images, pdfs)

### ISSUE THREAD

**Issue by Marvellanius** [ilestis/miscellany#22]
# Story
As a user, I want to be able to upload several files to an entity

# Work
TBD

# Tests
TBD

**Comment by mbglytch** [comment]
You mentionned AWS as a third party storage. Is there a [separation of concern](https://en.wikipedia.org/wiki/Separation_of_concerns) solution in Laravel to handle files ? On my own knowledge, in can mention [this plugin](https://github.com/burzum/cakephp-file-storage) (for cakePHP)

**Comment by ilestis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Entity: Upload Several Files](https://trello.com/c/IkDAloGv/16-entity-upload-several-files)
