### ISSUE TITLE
Calendar: Moon offset

### ISSUE THREAD

**Issue by Enkrod** [ilestis/miscellany#281]
### Story
As a user, I want to be able to offset the starting calculation of "moon every X days" from the first day of the first year.

### Dev
The "Moon every X days"-setting begins counting on the first day of year 0

An offset integer defaulting to 0 should be added to allow for things like a moon with a 28 days interval to be full on the 3rd day of the first year.

Requested by
GM of @Enkrod

**Comment by Enkrod** [comment]
I'll try my hand on a Pullrequest for this.

**Comment by ilestis** [comment]
> I'll try my hand on a Pullrequest for this.

Sounds good! Please make sure the UI works on mobile and desktop :)

**Comment by lucascalion** [comment]
Really nice idea. I'm also working on some scripts to show lunar phases and eclipses. Maybe I can work a PR for lunar phases in the calendar.

**Comment by ilestis** [comment]
I've added the moon offer in the developer branch, so closing this ticket :)
