### ISSUE TITLE
Trouble setting up locally

### ISSUE THREAD

**Issue by amazingrando** [ilestis/miscellany#283]
**Describe the bug**
I am attempting to install this project locally so that I can evaluate it for my gaming group as a replacement for our MediaWiki installation. If we adopt it, I'll likely contribute some frontend/design efforts back to this project. (I manage the Fate SRD and Blades in the Dark SRD, and like to contribute to RPG projects.)

I've read the README and I cannot get this project to work locally. Part of that is likely the small amount of knowledge that I have with Docker and the zero knowledge that I have with Laravel.

I would like it if there was more thorough instructions for setting this up locally. If that was the form of some hand-holding, I would be happy to write up the steps as documentation.

**To Reproduce**
Installation instructions are incomplete.

**Expected behavior**
I would like clear, step by step instructions

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser: N/A
 - Version: Pulling from `develop`

**Additional context**
Thank you for your efforts on this project and for making it open source.

**Comment by ilestis** [comment]
What kind of issues are you having? I don't use Docker myself, and the docs were provided by some users a while ago, so I'm not sure if any of it would work to this day.

If you had errors while setting up the database, with something like 
```
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table ltm_translations add
  unique ixk_ltm_translations_locale_group_key(locale, group, key)) 
```

Then you'll want to edit your `config/database.php` file and replace `'connections.mysql.engine'` from `null` to `'InnoDB ROW_FORMAT=DYNAMIC'`.

**Comment by amazingrando** [comment]
I was just on a work trip. I will try to circle back around to this sometime this week.

**Comment by pspeter3** [comment]
I think it would be nice if the Docker setup was also the default for local development. I'll look into seeing if I can make that work.

**Comment by pspeter3** [comment]
I'm seeing `/usr/local/bin/docker-php-entrypoint: 9: exec: /usr/local/bin/run.sh: Permission denied`. Is this the same error you were seeing @amazingrando?

**Comment by pspeter3** [comment]
I think https://github.com/ilestis/miscellany/pull/284 should help. I'm still getting a 404 though.

**Comment by amazingrando** [comment]
I'm trying to circle back around to this soon. Sorry, work has been busy.

**Comment by pspeter3** [comment]
After more investigation, I've discovered that the docker container works but is missing some configuration. You can load http://localhost:8000/index.php/en-US/about but not http://localhost:8000/en-US/about. @ilestis do you know what is missing?
