### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by ilestis** [ilestis/miscellany#286]
# Story
As a user, I want the app to be covered by unit tests.

# Setup
Determine how the db should be set up for tests. Is it empty and droped before tests are run, and tests run migrations first?

# Unit Tests
## Accounts
* Registering an account creates the account.
* Login in a user works as intended.
* Login in as an unknown user is rejected

## Campaigns
* Creating a campaign as a logged in user works (no mysql errors), using the `CampaignService`?
* Creating a campaign adds the user to the "is_admin" role of the campaign.
* The user has the "update" permission `auth()->user()->can('update', $campaign)` permission

## Campaign Roles
* The campaign admin can create a new role
* The campaign admin can't delete the "is_admin" or "is_public" roles (again using the laravel permissions)

## Campaign Members
* The campaign admin can invite a user using an email
* The campaign admin can create a new link to invite users with
* The campaign admin can delete invitations (email and links)
* A user can use the invitation to join a campaign (this might need refactoring or re-scoping of the test)

## Dashboard
* A campaign member can access the campaign's dashboard (should this be an integration test?)
* A campaign admin can edit the campaign dashboards (just check the permission?)

## Entities
* A campaign admin can create an entity of each type
* A campaign admin can delete an entity of each type

## Campaigns
* A logged in user can create a secondary campaign
* A logged in user can switch between their campaigns
* A logged in user can leave a campaign they own if they are not an admin
* A campaign admin can delete a campaign they are alone in
* A campaign admin can't delete a campaign that has several users

**Comment by ssltg** [comment]
I've made a PR for a basic implementation for tests. 
Take a Look: https://github.com/ssltg/miscellany/pull/1

**Comment by ilestis** [comment]
Oh wow, thanks for this! I've had a quick glance and it looks good. I'll test it during the week hopefully and get back to you :-)
