### ISSUE TITLE
Quest Locations & Character descriptions don't render @links

### ISSUE THREAD

**Issue by oakbrad** [ilestis/miscellany#289]
**Describe the bug**
When writing descriptions for the "Locations" and "Characters" sections under a "Quest", linking to other entities with @tags does not render the link in the appropriate view. Instead it shows [character:#] or other anchor, not a hyperlink.

**To Reproduce**
1.Create a new Quest
2. Add a Character or Location
3. Link with an @Tag in the description.
4. Go back to the Location/Character subsections on a quest and it will show the anchor instead of a link

**Expected behavior**
It should render the hyperlink with appropriate name.

**Screenshots**
Trying to @ link the barkeep in the description of a Location in the "Quest->Locations" view

![alt text](https://i.imgur.com/2TMa07l.png "example")

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 69

**Comment by ilestis** [comment]
This bug is fixed on the develop branch and will be deployed with an upcoming release. 
Please submit future bugs through the discord channel as I don't use github for error tracking.
