### ISSUE TITLE
Upload all user files to AWS storage

### ISSUE THREAD

**Issue by Marvellanius** [ilestis/miscellany#3]
# Story
As a user, I want the pictures that I upload on elements to be hosted on an external AWS server. Each file should be uploaded in a folder structure */userId/entityType/*.

# Work
1. An AWS storage needs to be created by u/Ilestis first.
2. When uploading content, the file needs to be saved on the AWS, with the new structure /userId/entityType/.
3. A script needs to be written to transfer the current files from the server to the new server in the new location, updating the models if necessary.

# Tests
* Uploading a file to an entity uploads it to AWS
* Viewing an entity shows the correct file
* Deleting an image works
* Overriding an image deletes the old one
* Resizing the image to the thumbnail works
* Old images have been transferred to the new server

**Comment by mbglytch** [comment]
@ilestis mentionned AWS as a third party storage. Is there a [separation of concern](https://en.wikipedia.org/wiki/Separation_of_concerns) solution in Laravel to handle files ? On my own knowledge, in can mention [this plugin](https://github.com/burzum/cakephp-file-storage) (for cakePHP)

**Comment by ilestis** [comment]
Yes, it is incredibly easy. We use the "storage" facade ( https://laravel.com/docs/5.6/filesystem ) using the "public disk", which would need to be replaced with an "aws" disk (and configured in the .env) to point to an aws. The tricky part would be a script that transfers the current images to the new location (also having a "campaign_id" in the path's root, to have all assets of a campaign together.
