### ISSUE TITLE
Upload images from an URL

### ISSUE THREAD

**Issue by Marvellanius** [ilestis/miscellany#5]
# Story
As a user, I want to be able to upload images from an url, as well as by selecting the file.

# Work
Maybe it's better to use an existing plugin for this.
* Allow upload of entity images to come from url. It should download the image locally, checking that it is indeed an image  (same validations as for file upload)

# Tests
Will depend if self-solution or plugin. 
* When creating a note, I can upload an image from an url
* When editing a journal, I can upload an image from an url
* Uploading from file still works
* Deleting file still works, independent on origin
* Uploading a mp3 through url doesn't work
* Works on mobile

**Comment by ilestis** [comment]
Implement something like this: http://plugins.krajee.com/file-input

- upload file
- upload from url
- delete previously uploaded file
