### ISSUE TITLE
Trim CR LF from copy paste

### ISSUE THREAD

**Issue by mbglytch** [ilestis/miscellany#64]
## Story

As a user, I want to be able to easily copy paste text from my pdf.

## Description

When i am editing entities content, i often copy paste text from pdf to textarea fields or wywiwyg fields. The text is often broken, with special `\n`, `\r` and `-` chars due to pdf columns design. Currently i haven't found any solution in the CKEditor options to trim those chars.

This behavior is getting worse when the CKEditor trim those chars when we submit the form.

## Work

In order to solve this problem, we need to replace `\n`, `\r` by ` `.

- Add a trim functionnality in javascript for textarea. Maybe a trim button outside of the `<textarea>` which will trigger the trim.

- Add a CKEditor plugin to trim selected text.

Or maybe a global hack in javascript who will listen to a custom keys combination (like `Ctrl `+ `i`) and will trim the selected text.

## Note

The javascript [String.prototype.replace()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) function should do the job.
`mystring.replace(/\r?\n|\r/g, " ");`

**Comment by ilestis** [comment]
That opens downloads 😬

**Comment by ilestis** [comment]
Rethinking about this, let's trim on copy-paste, but allow empty paragraphs when saving for people who want to manually enter them.
